object Versions {

    const val core = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val jUnit = "4.13.2"
    const val extJUnit = "1.1.3"
    const val espresso = "3.4.0"
    const val recyclerview = "28.0.0"
    const val lifecycle = "1.1.1"
    const val fragment = "2.4.1"
    const val runtime = "2.4.1"
    const val coroutines = "1.5.2"
    const val inject = "1"
    const val daggerCommon = "2.40.1"
    const val retrofit = "2.9.0"
    const val glide = "4.12.0"
    const val converterJson = "2.9.0"
    const val interceptor = "3.9.0"
    const val roomRuntime = "1.1.1"
    const val roomCompiler = "1.1.1"
}